---
abstract: 'modules for working with Excel .xls and .xlsx files'
author:
  - 'Nicolas Steenlant, C<< <nicolas.steenlant at ugent.be> >>'
build_requires: {}
configure_requires:
  Module::Build::Tiny: '0.036'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.017, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catmandu-XLS
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Catmandu: '0.9'
  Excel::Writer::XLSX: '0.77'
  Spreadsheet::ParseExcel: '0.65'
  Spreadsheet::WriteExcel: '2.37'
  Spreadsheet::XLSX: '0.13'
  XML::LibXML::Reader: '2.0'
  namespace::clean: '0.24'
  perl: v5.10.1
resources:
  bugtracker: https://github.com/LibreCat/Catmandu-XLS/issues
  homepage: https://github.com/LibreCat/Catmandu-XLS
  repository: https://github.com/LibreCat/Catmandu-XLS.git
version: '0.04'
x_contributors:
  - 'Johann Rolschewski <rolschewski@gmail.com>'
  - 'vpeil <vitali.peil@uni-bielefeld.de>'
